GET https://api.52vmy.cn/api/music/wy/top?t=1


###
GET https://api.52vmy.cn/api/music/wy/rand


###
GET https://api.52vmy.cn/api/img/tu/yuan
###
GET https://api.52vmy.cn/api/img/tu/cat

###
GET  https://api.52vmy.cn/api/video/jx?url=https://v.douyin.com/i8Upbh6w


###
GET https://api.52vmy.cn/api/img/fan?url=https://api.52vmy.cn/wx.png

###
GET https://api.52vmy.cn/api/img/heibai?url=https://api.52vmy.cn/wx.png


###
GET https://api.52vmy.cn/api/img/tu/girl

###
GET https://api.52vmy.cn/api/min?msg=骚逼水很多

###
GET https://api.52vmy.cn/api/query/fanyi/youdao?msg=你好吗？是的，我非常的好！


###
GET https://api.52vmy.cn/api/video/yule


###
GET https://api.52vmy.cn/api/video/redian

###
POST http://localhost:3000/api/hospital/visits/generate

###
GET https://api.kuleu.com/api/MP4_xiaojiejie?type=json


###
POST http://localhost:3000/app/video/download
X-Rapidapi-Key: e8a0cab8femsh32ae72fd76831c8p1a1993jsnd685db6b7c3a
Content-Type: application/json

{"video_link":"https://xnxx.com/video-wugb904/fucking_his_step_sister_lexxi_steele_in_high_definition"}

###
GET http://localhost:3000/app/video/download?video_link=https://xnxx.com/video-wugb904/fucking_his_step_sister_lexxi_steele_in_high_definition
X-Rapidapi-Key: e8a0cab8femsh32ae72fd76831c8p1a1993jsnd685db6b7c3a

###
GET http://localhost:3000/app/image/proxy?type=pussy